title:              Data Blog
email:              allanandrew.situma@gmail.com
description:        A blog for everything and anything about data
author:             Allan Situma
baseurl:            "/data-blog"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   allansituma
github_username:    AllanSituma
facebook_username:  allan-situma
instagram_username:  allan-situma
linkedin_username: allan-situma

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-cayman